### ISSUE TITLE
app.js accessible

### ISSUE THREAD

**Issue by steinbachio** [plesk/node-express#1]
First things first:
Thank you very much for this project!

if you go to domain.tld/app.js, it renders your app.js file.

best,
Marius

**Comment by sibprogrammer** [comment]
You should put the content of the app into "my-app-dir" (for example) but change the doc root to "my-app-dir/public". In such case app.js will be inaccessible. You can find additional details here: https://www.plesk.com/blog/product-technology/node-js-plesk-onyx/
