### ISSUE TITLE
My node.js app not working on Plesk and always Shows "(URL Rewrite Module Error.)"

### ISSUE THREAD

**Issue by anju224** [plesk/node-express#2]
Hi,
I have hosting with host4asp.net and recently we have uploaded app.I have follow all the steps in "https://github.com/plesk/node-express" but still i am getting error.

My app run fine on local server but that not on hosting server and always generate errror.
This app built with MEAN.You can see error:http://99near.com/.

I have uploaded same site on subdomain that showing different error.Url of subdomain"http://216.104.43.254/plesk-site-preview/99n.99near.com/"

Thanks,

**Comment by anju224** [comment]
I have uploaded same site on subdomain that showing different error.Url of subdomain"http://216.104.43.254/plesk-site-preview/99n.99near.com/"

**Comment by sibprogrammer** [comment]
Close stalled requests.
