### ISSUE TITLE
example project doesn't work on Plesk Obsidian

### ISSUE THREAD

**Issue by clemensmol** [plesk/node-express#7]
Installed the app, and followed directions on your site. Keep getting "Error starting web application" errors from Phusion Passenger. 

Subprocess:
Initialize language runtime — 0.1s
Load or execute application — 89.9s

**Comment by clemensmol** [comment]
I found the solution. Plesk bugs when main folder and application folders are the same for Node apps. No errors are shown in the Panel but when I added a public folder it started to work.

**Comment by Brian-Graham** [comment]
@clemensmol What exactly did you do to fix this? I think I've just ran into the exact same problem.

Where are your files in relation to the web root, and what are your plesk settings for the node app (application root, document root, application startup file)?

**Comment by CaptainLazarus** [comment]
Any updates? Think I've just run into this.

**Comment by clemensmol** [comment]
Sorry @Nahydrin, somehow I missed your question. Maybe it's helpful for @CaptainLazarus.
I'm running a NextJS site with node 16.13.1

## Dir structure:
- /var/www/vhosts/domain
- /var/www/vhosts/domain/live
- /var/www/vhosts/domain/live/public (this is an autogenerated folder from NextJS with all the static assets)


## Plesk NodeJS settings:
Document Root:  /var/www/vhosts/domain/live/public
Application Root:  /var/www/vhosts/domain/live
Application Startup File: server.js (this file must exist in /var/www/vhosts/domain/live)

The Document Root is for hosting static assets (images, robots.txt etc). The Application Root is where your NodeJS code exists. The Application Startup File points to a file inside the Application Root, usually the file running your (Express) server.
